# Generated by Django 5.2.15 on 2026-07-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preview_video',
            field=models.FileField(blank=True, upload_to='projects/previews/'),
        ),
    ]
