# Generated by Django 5.2.15 on 2026-07-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_project_preview_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='preview_video',
        ),
    ]
