# Generated by Django 5.2.15 on 2026-07-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_remove_project_preview_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Card cover shown before video hover. For comics, use the cover page.', upload_to='projects/thumbnails/'),
        ),
    ]
