# Generated by Django 5.2.15 on 2026-07-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmedia',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
