# Generated by Django 5.2.15 on 2026-07-10 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_projectmedia_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='projects/comics/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic_pages', to='works.project')),
            ],
            options={
                'ordering': ['page_number'],
                'constraints': [models.UniqueConstraint(fields=('project', 'page_number'), name='unique_comic_page_number')],
            },
        ),
    ]
