# Generated by Django 5.2.15 on 2026-07-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_comicpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicpage',
            name='caption',
        ),
    ]
