# Generated by Django 5.2.15 on 2026-07-11 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_remove_comicpage_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.ImageField(blank=True, upload_to='projects/episodes/thumbnails/')),
                ('featured_image', models.ImageField(upload_to='projects/episodes/featured/')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='comicpage',
            name='unique_comic_page_number',
        ),
        migrations.AddField(
            model_name='project',
            name='format',
            field=models.CharField(choices=[('single', 'Single'), ('series', 'Series')], default='single', help_text='Single or series. Applies to film and comic projects.', max_length=20),
        ),
        migrations.AlterField(
            model_name='comicpage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comic_pages', to='works.project'),
        ),
        migrations.AddField(
            model_name='seriesepisode',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='works.project'),
        ),
        migrations.AddField(
            model_name='comicpage',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comic_pages', to='works.seriesepisode'),
        ),
        migrations.AddField(
            model_name='projectmedia',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='works.seriesepisode'),
        ),
        migrations.AddConstraint(
            model_name='comicpage',
            constraint=models.UniqueConstraint(condition=models.Q(('episode__isnull', True)), fields=('project', 'page_number'), name='unique_comic_page_number'),
        ),
        migrations.AddConstraint(
            model_name='comicpage',
            constraint=models.UniqueConstraint(condition=models.Q(('episode__isnull', False)), fields=('episode', 'page_number'), name='unique_episode_comic_page_number'),
        ),
        migrations.AddConstraint(
            model_name='seriesepisode',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='unique_series_episode_number'),
        ),
    ]
