# Generated by Django 5.2.15 on 2026-07-12 09:00

import works.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_project_format_and_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicpage',
            name='image',
            field=models.ImageField(upload_to='projects/comics/', validators=[works.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(upload_to='projects/featured/', validators=[works.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Card cover shown before video hover. For comics, use the cover page.', upload_to='projects/thumbnails/', validators=[works.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='media_file',
            field=models.FileField(blank=True, upload_to='projects/media/', validators=[works.validators.validate_media_upload]),
        ),
        migrations.AlterField(
            model_name='seriesepisode',
            name='featured_image',
            field=models.ImageField(upload_to='projects/episodes/featured/', validators=[works.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='seriesepisode',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='projects/episodes/thumbnails/', validators=[works.validators.validate_image_upload]),
        ),
        migrations.AddIndex(
            model_name='anonymouscomment',
            index=models.Index(fields=['ip_address', 'created_at'], name='works_anony_ip_addr_c77552_idx'),
        ),
    ]
