# Generated by Django 5.2.15 on 2026-07-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_comment_ip_index_and_upload_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delivery_formats',
            field=models.CharField(blank=True, help_text='For advertising projects: comma-separated list, e.g. YouTube, TV, Reels.', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('software', 'Software'), ('film', 'Film'), ('comic', 'Comic'), ('advertising', 'Advertising'), ('lab', 'Lab')], max_length=20),
        ),
    ]
