# Generated by Django 5.2.15 on 2026-07-14 09:10

import works.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_optional_detail_covers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesepisode',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional 4:5 card cover for episode cards.', upload_to='projects/episodes/thumbnails/', validators=[works.validators.validate_image_upload]),
        ),
    ]
